version: "3.7"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/src:/var/www/html/src
    ports:
      - "90:80"
    restart: unless-stopped
