version: "3.8"
services:
  app:
    container_name: react_typescript
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ..:/workspaces:cached
      # - ${HOME}${USERPROFILE}/.aws:/root/.aws
      - ./.aws:/root/.aws
      - ${HOME}${USERPROFILE}/.git:/root/.git
    ports:
      - "3000:3000"
    # プロセスが終了してコンテナが終了してしまわないように
    # command: /bin/sh -c "while sleep 1000; do :; done"
    tty: true
    restart: unless-stopped
